import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BookDetailsContextProvider } from "@/context/book-details";
import { Toaster } from "@/components/ui/toaster";
import { inter } from "@/lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-[hsl(215,28%,12%)] text-gray-300`}
      >
        <BookDetailsContextProvider>{children}</BookDetailsContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
