import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { BookDetailsContextProvider } from "@/context/book-details";
import { Geist, Geist_Mono } from "next/font/google";
import { inter } from "@/lib/fonts";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-background text-gray-300`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <BookDetailsContextProvider>
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full">
                <Header />
                {children}
              </main>
            </SidebarProvider>
          </BookDetailsContextProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
